template: Hello, %s!
defaultName: ${defaultName:-Stranger}

swagger:
  resourcePackage: playground.dropwizard.resource

server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ${logDir:-logs}/access.log
        archivedLogFilenamePattern: ${logDir:-logs}/access.%d.log.gz
